# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)
#
language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli grunt-mocha-test
intall: npm install
before_script: grunt
